/- BLD Calculus — Type Grammar

   Reference: bld-calculus.md Definition 2.1

   The types of the BLD calculus are generated by three constructors
   corresponding to the three primitives:
     B (Boundary) → Sum type (τ₁ + τ₂)
     L (Link)     → Function type (τ₁ → τ₂)
     D (Dimension) → n-fold product (Πₙτ)
-/

/-- BLD calculus types. -/
inductive Ty : Type where
  | unit : Ty                    -- 1
  | sum  : Ty → Ty → Ty         -- B: τ₁ + τ₂
  | fn   : Ty → Ty → Ty         -- L: τ₁ → τ₂
  | prod : Nat → Ty → Ty        -- D: Πₙ(τ)
  deriving Repr, DecidableEq

namespace Ty

/-- Bool = 1 + 1.  Reference: bld-calculus.md Corollary 7.4 -/
def Bool : Ty := .sum .unit .unit

end Ty
